### ISSUE TITLE
Langserver configuration: adding settings to the default configuration doesn't work

### ISSUE THREAD

**Issue by rdbende** [Akuli/porcupine#1117]
`pyls` in my case.

Let's say I want to use [`flake8-tkinter`](https://github.com/rdbende/flake8-tkinter), or basically any flake8 plugin in Porcupine.
Since flake8 is disabled by default in Pyls, I can't. Other editors that use Pyls, like Neovim (ok, the LanguageClient plugin) provide a easy configuration for the langserver.

**Comment by Akuli** [comment]
It is already possible to set some langserver configuration options. For pyls, porcupine sets:

https://github.com/Akuli/porcupine/blob/ce9730b9903c376deeb1ffb359671378f42bf1b7/porcupine/default_filetypes.toml#L175-L176

which tells pyls to use the correct virtualenv.

Also, I don't like pyls for various reasons, and there is an issue about replacing it: #560

**Comment by rdbende** [comment]
This works:

```toml
[Python.langserver.settings.pyls.plugins.flake8]
enabled = true
```

But only if I put it into `default_filetypes.toml`. If I put it into `~/.config/porcupine/filetypes.toml`, I get all kinds of `dacite` errors.

**Comment by Akuli** [comment]
The bug is caused by this code in `filetypes.py`:

```python3
    with defaults_path.open("rb") as defaults_file:
        filetypes.update(tomli.load(defaults_file))
    ...
    for name, updates in user_filetypes.items():
        filetypes.setdefault(name, {}).update(updates)
```

Instead of a hard-coded one level of updating, it should do a recursive dict merge. Currently you can add more settings to the `Python` section, but not into any of its subsections.

**Comment by rdbende** [comment]
So this works:

`filetypes.toml`:

```toml
# bla bla bla

[Python.langserver]
command = "{porcupine_python} -m pyls"
language_id = "python"

[Python.langserver.settings.pyls.plugins.flake8]
enabled = true
```
