### ISSUE TITLE
slowness with indent/dedent in huge file

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#176]
Notice that indent and dedent happens quickly, but "is file saved" marker updates slowly (`*__init__.pyi*` vs `__init__.pyi` at top):

https://user-images.githubusercontent.com/18505570/103459022-c8e3f780-4d14-11eb-89dc-6cfcc35aa6e3.mp4

This is a huge file, with 2670 lines in it

I have disabled the syntax highlighting in `filetypes.toml` to work around #39

```toml
["Python stub file"]
pygments_lexer = "pygments.lexers.TextLexer"
```
