### ISSUE TITLE
mako-templates

### ISSUE THREAD

**Issue by Akuli** [Akuli/porcupine#440]
I have a project with files like `mako-templates/hello.html`. I tried adding this to filetypes.toml:

```toml
['Mako HTML']
filename_patterns = ["mako-templates/*.html"]
pygments_lexer = 'pygments.lexers.MakoHtmlLexer'
```

This doesn't work. Even `["*.html"]` doesn't work, without this small modification to Porcupine:

```diff
diff --git a/porcupine/plugins/filetypes.py b/porcupine/plugins/filetypes.py
index 9de5277..9c1c5d8 100644
--- a/porcupine/plugins/filetypes.py
+++ b/porcupine/plugins/filetypes.py
@@ -77,8 +77,8 @@ def get_filetype_from_matches(
     if not matches:
         return None

-    [result, *rest] = matches.values()
+    [*rest, result] = matches.values()
     if rest:
         names = ', '.join(matches.keys())
         log.warning(f"multiple file types match {they_match_what}: {names}")
     return result
```
